language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'famous' ]; then cd .. && eval "mv $currentfolder famous" && cd core; fi

notifications:
  email:
    - mike@famo.us
    - myles@famo.us
